---
kind: pipeline
name: build
type: docker

concurrency:
  limit: 1

steps:
- name: laravel
  image: lbausch/laravel-ci:php82
  commands:
  - composer install --ansi --no-interaction --no-progress --no-dev -o
  - npm i -g yarn
  - yarn install
  
  # probably build things?  IDK

- name: rsync
  image: drillster/drone-rsync
  settings:
    hosts: [10.10.0.23]
    user: doeggscostmore.com
    key:
      from_secret: deploy_key
    port: 2222
    target: /home/web/html/
    source: ./*
    delete: true
    recursive: true
  when:
    branch:
      - master

- name: deploy
  image: appleboy/drone-ssh
  settings:
    host:
      - 10.10.0.23
    username: doeggscostmore.com
    key:
      from_secret: deploy_key
    port: 2222
    command_timeout: 5m
    script: |
      cp /home/web/.env /home/web/html/.env